version: "3"
services:

  postgres:
    image: postgres:13
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./import/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.2
    network_mode: bridge
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./import/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: unless-stopped

  challenge-api:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: challenge-api
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - mongodb
      - postgres
    restart: unless-stopped